language: ruby
sudo: required

services:
  - docker

rvm:
  - 2.5.1

install:
 - bundle install --jobs=3 --retry=3
 - gem install kitchen-inspec

cache:
  directories:
  - vendor/bundle

script:
  - bundle exec kitchen test --concurrency

notifications:
  disable: true
